import re, sys, os

def strip_dart_comments(content):
    lines = content.split('\n')
    result = []
    in_block_comment = False
    
    for line in lines:
        if in_block_comment:
            end_idx = line.find('*/')
            if end_idx != -1:
                in_block_comment = False
                remainder = line[end_idx + 2:]
                if remainder.strip():
                    result.append(remainder)
            continue
        
        # Skip lines that are only comments (// ...)
        stripped = line.strip()
        
        # Keep the file: ignore_for_file lines (they're pragmas, not comments)
        if stripped.startswith('// ignore_for_file'):
            result.append(line)
            continue
        
        # Skip firebase_options.dart generated file comments
        if stripped.startswith('// File generated by'):
            result.append(line)
            continue
            
        # Pure comment line
        if stripped.startswith('//'):
            continue
        
        # Block comment start
        if stripped.startswith('/*'):
            end_idx = line.find('*/')
            if end_idx == -1:
                in_block_comment = True
            continue
        
        # Line with trailing comment - remove comment but keep code
        # Be careful with strings containing //
        new_line = remove_trailing_comment(line)
        result.append(new_line)
    
    # Remove excessive blank lines (3+ consecutive -> 2)
    cleaned = []
    blank_count = 0
    for line in result:
        if line.strip() == '':
            blank_count += 1
            if blank_count <= 2:
                cleaned.append(line)
        else:
            blank_count = 0
            cleaned.append(line)
    
    return '\n'.join(cleaned)

def remove_trailing_comment(line):
    in_single_quote = False
    in_double_quote = False
    escaped = False
    i = 0
    while i < len(line):
        c = line[i]
        if escaped:
            escaped = False
            i += 1
            continue
        if c == '\\':
            escaped = True
            i += 1
            continue
        if c == "'" and not in_double_quote:
            in_single_quote = not in_single_quote
        elif c == '"' and not in_single_quote:
            in_double_quote = not in_double_quote
        elif c == '/' and not in_single_quote and not in_double_quote:
            if i + 1 < len(line) and line[i + 1] == '/':
                return line[:i].rstrip()
        i += 1
    return line

root = sys.argv[1]
count = 0
for dirpath, _, filenames in os.walk(root):
    for f in filenames:
        if not f.endswith('.dart'):
            continue
        filepath = os.path.join(dirpath, f)
        with open(filepath, 'r') as fh:
            original = fh.read()
        cleaned = strip_dart_comments(original)
        if cleaned != original:
            with open(filepath, 'w') as fh:
                fh.write(cleaned)
            count += 1
            print(f"  Cleaned: {filepath}")
print(f"\nDone. {count} files modified.")
